name: 'currency_exchange'

on:
  push:
    branches: [ "main" ]
    paths:
     - 'src/**'
     - 'infra/**'

permissions:
  contents: read

jobs: 
  currency_exchange:
    name: 'currency_exchange'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Zip the Cloud Function source code
    - name: Zip Cloud Function Source
      run: |
        cd src/extract
        zip -r project-currency-exchange.zip .
        mv project-currency-exchange.zip ../../infra/

    # Google Cloud authentication
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CURRENCY_EXCHANGE_KEY }}

    # Set up Google Cloud SDK (store credentials securely!)
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.1
      with:
        project_id: portfolio-436507
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_CURRENCY_EXCHANGE_KEY }}

    # Install Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.8.5

    # Initialize Terraform working directory
    - name: Terraform Init
      run: terraform init && if [ $? -ne 0 ]; then exit 1; fi
      working-directory: infra/

    # Terraform Format
    - name: Terraform Format
      run: terraform fmt && if [ $? -ne 0 ]; then exit 1; fi
      working-directory: infra/

    # Generate Terraform execution plan
    - name: Terraform Plan
      run: terraform plan -input=false && if [ $? -ne 0 ]; then exit 1; fi
      working-directory: infra/

    # Apply Terraform changes (only on push to main)
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false && if [ $? -ne 0 ]; then exit 1; fi
      working-directory: infra/